# -*- coding: utf-8 -*-
"""Command line wrapper for V32 field-trace patch.

This wrapper keeps the old script-style invocation instead of forcing callers to
import FieldTraceEngine manually.

Python 2.7 compatible.
"""
from __future__ import print_function

import argparse
import os
import re
import sys

from .v32_field_trace import FieldTraceEngine


def read_text(path):
    with open(path, 'rb') as f:
        data = f.read()
    try:
        return data.decode('utf-8')
    except Exception:
        try:
            return data.decode('gbk')
        except Exception:
            return data.decode('utf-8', 'ignore')


def write_text(path, text):
    parent = os.path.dirname(path)
    if parent and not os.path.exists(parent):
        os.makedirs(parent)
    if not isinstance(text, bytes):
        text = text.encode('utf-8')
    with open(path, 'wb') as f:
        f.write(text)


def find_execute_ins_relebook(c_text):
    """Find EXEC SQL EXECUTE INS_RELEBOOK USING ...; blocks.

    Supports single-line and simple multi-line EXEC SQL blocks.
    """
    pattern = re.compile(
        r'EXEC\s+SQL\s+EXECUTE\s+INS_RELEBOOK\s+USING\s+.*?;',
        re.I | re.S
    )
    return pattern.findall(c_text or '')


def build_output(engine, c_text, target_tables):
    stmts = find_execute_ins_relebook(c_text)
    lines = []
    lines.append('-- V32 generated field-trace patch output')
    lines.append('-- NOTE: This wrapper only emits V32 INS_RELEBOOK pre-insert assignment logic.')
    lines.append('-- It is used to verify and merge V32 logic into the full converter.')
    lines.append('')

    if not stmts:
        lines.append('-- TODO V32: 未找到 EXEC SQL EXECUTE INS_RELEBOOK USING 语句。')
        return '\n'.join(lines) + '\n'

    for target_table in target_tables:
        target_table = target_table.strip()
        if not target_table:
            continue
        lines.append('-- ============================================================')
        lines.append('-- TARGET TABLE: %s' % target_table)
        lines.append('-- ============================================================')
        for idx, stmt in enumerate(stmts, 1):
            lines.append('-- EXECUTE INS_RELEBOOK #%s' % idx)
            assign_sql = engine.prepare_before_insert_for_execute(stmt, target_table)
            if assign_sql:
                lines.append(assign_sql)
            lines.append('')
            lines.append('-- V32 replaced EXECUTE USING preview')
            lines.append(engine.replace_srelebook_using_vars(stmt))
            lines.append('')
            lines.append('INSERT INTO %s (...) VALUES (...); -- TODO: full INSERT columns generated by main converter' % target_table)
            lines.append('')
    return '\n'.join(lines) + '\n'


def parse_args(argv):
    p = argparse.ArgumentParser(description='V32 C -> Gauss SReleBook field trace wrapper')

    # Keep old-style and new-style aliases together.
    p.add_argument('--c-file', '--input', '--source', dest='c_file', required=True,
                   help='C/Pro*C source file path')
    p.add_argument('--loader-cfg', '--cfg', dest='loader_cfg', required=True,
                   help='Loader cfg file path')
    p.add_argument('--middle-table', dest='middle_table', default='',
                   help='Middle table name, kept for compatibility with old command style')
    p.add_argument('--middle-alias', dest='middle_alias', default='R',
                   help='Middle table row alias. Default: R')
    p.add_argument('--out-dir', '--output-dir', '--output', dest='out_dir', default='output',
                   help='Output directory. Default: output')
    p.add_argument('--target-table', action='append', dest='target_tables', default=[],
                   help='Target table. Can be repeated. Default: EVDAT_CXRELEBOOK and EVHIS_CXRELEBOOKHIS')
    p.add_argument('--sql-name', dest='sql_name', default='v32_relebook_patch.sql',
                   help='Output sql file name. Default: v32_relebook_patch.sql')
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv or sys.argv[1:])
    c_text = read_text(args.c_file)
    cfg_text = read_text(args.loader_cfg)

    engine = FieldTraceEngine(middle_alias=args.middle_alias)
    engine.build_cfg_map(cfg_text)
    engine.record_source(c_text, 1)

    target_tables = args.target_tables or ['EVDAT_CXRELEBOOK', 'EVHIS_CXRELEBOOKHIS']
    sql_text = build_output(engine, c_text, target_tables)

    sql_path = os.path.join(args.out_dir, args.sql_name)
    review_path = os.path.join(args.out_dir, 'review.md')
    write_text(sql_path, sql_text)
    write_text(review_path, engine.review.to_markdown())

    print('V32 output sql: %s' % sql_path)
    print('V32 review   : %s' % review_path)
    if args.middle_table:
        print('Middle table : %s' % args.middle_table)
    return 0


if __name__ == '__main__':
    sys.exit(main())
